### ISSUE TITLE
small issues in advanced settings

### ISSUE THREAD

**Issue by drahti** [MajorMJR/factorio-server-manager#11]
hey,

I just got my "production instance" working
I noticed a couple of issues so far. In the Advanced Settings on the main page a couple of checkboxes are misaligned. Also the checkbox "Auto Pause when no players connected" is labelled wrong, checking it will cause the server NOT to auto pause when no players connected. 

Last but not least if I edit the autosave slots for example, I'd love if the application could somehow save the values and show the updated values the next time I visit this page. 

All minor annoyances, nothing which actually disturbes me. I just wanted you to know about this. 

![image](https://cloud.githubusercontent.com/assets/15235838/14931902/c150793c-0e6f-11e6-99a0-8c2bef2f78c9.png)

**Comment by MajorMJR** [comment]
Yeah I have been trying to get those silly checkboxes aligned.  Just an issue with Bootstrap, I'll figure out what is causing the misalignment for the next release.

Correcting the label is easy if anyone wants to take a look, otherwise I'll correct it in a little while.

Persisting the values is a good idea and would help with the UX, persisting them without a page load is easy, just have to update this.state with the current values of the form.  I'll have to take a look at persisting changes after reloading the page, maybe just store the values in a cookie or web storage.

**Comment by MajorMJR** [comment]
Fixed all these issues, they'll be included in the next release.
